# Generated by Django 3.1 on 2020-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20200819_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default/logo-restaurant-default.jpg', upload_to='restaurant-images', verbose_name='Logo de Restaurante'),
        ),
    ]
