# Generated by Django 3.1 on 2020-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200819_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='restaurant-images', verbose_name='Logo de Restaurante'),
        ),
    ]
