# Generated by Django 3.1 on 2020-08-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20200819_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_hours',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
