# Generated by Django 3.1 on 2020-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(choices=[('USD', '&#36;'), ('ARS', '&#36;'), ('BOB', '&#36;&#98;'), ('BRL', '&#82;&#36;'), ('CLP', '&#36;'), ('CRC', '&#8353;'), ('COP', '&#36;'), ('EUR', '&#8364;'), ('MXN', '&#36;'), ('PAB', '&#66;&#47;&#46;'), ('PEN', '&#83;&#47;&#46;'), ('UYU', '&#36;&#85;'), ('VEF', '&#66;&#115;')], default='USD', max_length=30),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
