# Generated by Django 3.1 on 2020-08-24 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transactionId',
        ),
    ]
