# Generated by Django 3.1 on 2020-08-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_order_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
