# Generated by Django 3.1 on 2020-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_restaurant_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
