# Generated by Django 3.1 on 2020-08-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
