# Generated by Django 3.1 on 2020-09-24 16:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_auto_20200924_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='store_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
